export const ROLES = {
  ADMIN: "ADMIN",
  MANAGER: "MANAGER",
  STORE_MANAGER: "STORE_MANAGER",
  STAFF: "STAFF",
  VIEWER: "VIEWER",
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const ROLE_LABELS: Record<Role, string> = {
  ADMIN: "Admin",
  MANAGER: "Manager",
  STORE_MANAGER: "Store Manager",
  STAFF: "Staff",
  VIEWER: "Viewer",
};

export const PRODUCT_WRITE_ROLES: Role[] = [ROLES.ADMIN, ROLES.MANAGER, ROLES.STORE_MANAGER];
export const PRODUCT_DELETE_ROLES: Role[] = [ROLES.ADMIN];
export const INVENTORY_OPERATION_ROLES: Role[] = [
  ROLES.ADMIN,
  ROLES.MANAGER,
  ROLES.STORE_MANAGER,
  ROLES.STAFF,
];
export const SALES_WRITE_ROLES: Role[] = [ROLES.ADMIN, ROLES.MANAGER, ROLES.STORE_MANAGER, ROLES.STAFF];
export const PURCHASE_WRITE_ROLES: Role[] = [ROLES.ADMIN, ROLES.MANAGER, ROLES.STORE_MANAGER, ROLES.STAFF];
export const ANALYTICS_ROLES: Role[] = [ROLES.ADMIN, ROLES.MANAGER, ROLES.STORE_MANAGER, ROLES.VIEWER];
export const DEMAND_INTELLIGENCE_ROLES: Role[] = [ROLES.ADMIN, ROLES.MANAGER, ROLES.STORE_MANAGER];
export const USER_MANAGEMENT_ROLES: Role[] = [ROLES.ADMIN];
export const SETTINGS_ROLES: Role[] = [ROLES.ADMIN];
