"""create_purchases_table

Revision ID: 1ed61ac487df
Revises: 31cc35d5ea15
Create Date: 2026-07-03 14:07:47.309609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ed61ac487df'
down_revision: Union[str, Sequence[str], None] = '31cc35d5ea15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('supplier_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cost_price > 0', name='chk_purchase_cost_price'),
    sa.CheckConstraint('quantity > 0', name='chk_purchase_quantity'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_purchases_created_at', 'purchases', ['created_at'], unique=False)
    op.create_index('idx_purchases_product_id', 'purchases', ['product_id'], unique=False)
    op.create_index('idx_purchases_supplier_name', 'purchases', ['supplier_name'], unique=False)
    op.create_index(op.f('ix_purchases_id'), 'purchases', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchases_id'), table_name='purchases')
    op.drop_index('idx_purchases_supplier_name', table_name='purchases')
    op.drop_index('idx_purchases_product_id', table_name='purchases')
    op.drop_index('idx_purchases_created_at', table_name='purchases')
    op.drop_table('purchases')
    # ### end Alembic commands ###
