"""create_sales_table

Revision ID: 31cc35d5ea15
Revises: d0529fb6cf96
Create Date: 2026-07-03 14:04:15.021584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31cc35d5ea15'
down_revision: Union[str, Sequence[str], None] = 'd0529fb6cf96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='chk_sale_quantity'),
    sa.CheckConstraint('selling_price >= 0', name='chk_sale_selling_price'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sales_created_at', 'sales', ['created_at'], unique=False)
    op.create_index('idx_sales_customer_name', 'sales', ['customer_name'], unique=False)
    op.create_index('idx_sales_product_id', 'sales', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_index('idx_sales_product_id', table_name='sales')
    op.drop_index('idx_sales_customer_name', table_name='sales')
    op.drop_index('idx_sales_created_at', table_name='sales')
    op.drop_table('sales')
    # ### end Alembic commands ###
