"""create users table

Revision ID: 3ddf52bfa3a4
Revises: ca42c647aa96
Create Date: 2026-07-07 23:14:19.325284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ddf52bfa3a4'
down_revision: Union[str, Sequence[str], None] = 'ca42c647aa96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_inventory_product_id'), 'inventory', type_='unique')
    op.add_column('users', sa.Column('full_name', sa.String(length=150), nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.drop_column('users', 'username')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'full_name')
    op.create_unique_constraint(op.f('uq_inventory_product_id'), 'inventory', ['product_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
