"""make inventory product unique

Revision ID: ca42c647aa96
Revises: 3a4acb3ca90e
Create Date: 2026-07-06 23:11:37.487894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca42c647aa96'
down_revision: Union[str, Sequence[str], None] = '3a4acb3ca90e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_inventory_product_id'), 'inventory', ['product_id'], unique=True)
    op.create_unique_constraint(
        "uq_inventory_product_id",
        "inventory",
        ["product_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_inventory_product_id",
        "inventory",
        type_="unique"
    )
    op.drop_index(op.f('ix_inventory_product_id'), table_name='inventory')
    # ### end Alembic commands ###
