"""create_inventory_transaction_table

Revision ID: d0529fb6cf96
Revises: 79ccba5fa6b7
Create Date: 2026-07-03 14:00:41.338693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0529fb6cf96'
down_revision: Union[str, Sequence[str], None] = '79ccba5fa6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("transaction_type IN ('IN', 'OUT', 'ADJUSTMENT')", name='chk_transaction_type'),
    sa.CheckConstraint('quantity > 0', name='chk_transaction_quantity'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_trans_created_at', 'inventory_transactions', ['created_at'], unique=False)
    op.create_index('idx_inv_trans_product_id', 'inventory_transactions', ['product_id'], unique=False)
    op.create_index('idx_inv_trans_reference', 'inventory_transactions', ['reference'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_id'), 'inventory_transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_transactions_id'), table_name='inventory_transactions')
    op.drop_index('idx_inv_trans_reference', table_name='inventory_transactions')
    op.drop_index('idx_inv_trans_product_id', table_name='inventory_transactions')
    op.drop_index('idx_inv_trans_created_at', table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    # ### end Alembic commands ###
